# ~/.config/hyprtoolkit/hyprtoolkit.conf
# Couleurs (Format 0xAARRGGBB)
background = 0xFF282828
base = 0xFF3C3836
text = 0xFFEBDBB2
accent = 0xFFFE8019
accent_secondary = 0xFF8EC07C

# Polices
font_family = Terminus
font_family_monospace = Terminus
font_size = 12

# Interface
rounding_large = 0
rounding_small = 0
